version: "3"

services:
  webserver:
    build:
      context: ./webserver
    container_name: "navid-webserver"
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    volumes:
      - ./www:/var/www/html
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2

  mysql:
    build: ./db
    container_name: "mysql"
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: navid7373
      MYSQL_DATABASE: Axxes
      MYSQL_USER: root
      MYSQL_PASSWORD: navid7373
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "navid-phpmyadmin"
    restart: "always"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    volumes:
      - /sessions

  backend:
    build: ./backend
    environment:
      MYSQL_DATABASE: Axxes
      MYSQL_USER: root
      MYSQL_PASSWORD: navid7373
      MYSQL_PORT: 3306
      DATABASE_HOST: mysql
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    restart: on-failure

  portainer:
    image: portainer/portainer
    container_name: "navid-management"
    command: -H unix:///var/run/docker.sock
    restart: "always"
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data:
