version: "3"

services:
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: Axxes
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      DATABASE_HOST: db
    restart: always
    volumes:
      - mysqldata

  web:
    build: ./web
    environment:
      MYSQL_DATABASE: Axxes
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_PORT: 3306
      DATABASE_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
